/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/RLApDw8kgQa
 */
"use client";
import Link from "next/link"
import { ArrowDownIcon, ArrowRightIcon } from "@/components/ui/icons/arrow-icons"
import { getYearsAgo, prependRequest } from "@/lib/utils"
import { ProjectCard } from "@/components/project-card"
import { SkillCard } from "@/components/skill-card"
import skills from "@/configs/skills.json"
import DynamicView from "@/lib/dynamic-view"
import { TypeAnimation } from "react-type-animation"
import { useEffect, useState } from "react";
import { Project } from "@/lib/interfaces";


export default function Component() {
  const [projects, setProjects] = useState<Array<Project>>([])

  useEffect(() => {
    fetch(prependRequest("/projects?starred=true"), {

    }).then((res) => res.json())
      .then((data) => {
        setProjects(data?.projects || [])
      })
      .catch((err) => {
        console.error(err)
      })
  }, [])
  return (
    <div className="flex flex-col min-h-[100dvh] ">
      <header className="h-14 flex items-center justify-end w-[100vw]">
        <div className="px-4 md:px-6 flex items-center gap-4s">
          <nav className="ml-auto flex gap-4 md:gap-6">
            <Link className="text-,d font-medium hover:underline underline-offset-4" href="#about">
              About
            </Link>
            <Link className="text-md font-medium hover:underline underline-offset-4" href="#projects">
              Projects
            </Link>
            <Link className="text-md font-medium hover:underline underline-offset-4" href="#skills">
              Skills
            </Link>
          </nav>
        </div>
      </header>
      <main className="grid gap-6 lg:gap-12 xl:gap-16 mt-8 sm:mt-0">
        <section id="#about" className="grid gap-6 lg:grid-cols-2 lg:h-[calc(100vh-14px)] md:grid-cols-2 md:h-[calc(100vh-14px)] w-full">
          <div className="px-4 md:px-6 flex flex-col justify-center space-y-4">
            <div className="grid space-y-2">
              <TypeAnimation
                className="text-4xl font-bold tracking-tighter lg:text-5xl xl:text-6xl/none mt-1"
                sequence={[
                  "Hi, My name is Thayan Sivathevan"
                ]}
                wrapper="span"
                cursor={false}
              />
              <TypeAnimation
                className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400"
                sequence={[
                  2200,
                  `I am a dedicated and passionate full stack software engineer with over ${getYearsAgo(2022)} years of experience in the industry. I have a strong foundation in computer science and software engineering principles. I am a quick learner and a team player who is passionate about creating impactful solutions.`
                ]}
                wrapper="span"
                cursor={false}
                speed={99}
              />
            </div>
            <div className="flex flex-col gap-2 md:flex-row md:place-items-center">
              <Link
                className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm gap-2 transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                href="https://www.linkedin.com/in/thayan-sivathevan/"
              >
                View Linkedin
                <ArrowRightIcon className="w-4 h-4 peer-[translate-x-1]" />
              </Link>
              <Link
                className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm gap-2 transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                href="https://github.com/ThayanSivathevan"
              >
                View Github
                <ArrowRightIcon className="w-4 h-4 peer-[translate-x-1]" />
              </Link>
              <a
                className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm gap-2 transition-colors hover:bg-gray-100 hover:text-gray-900 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:focus-visible:ring-gray-300 dark:border-gray-800"
                href="ThayanSivathevan_Resume.pdf"
                download
              >
                Download Resume
                <ArrowDownIcon className="w-4 h-4 peer-[translate-x-1]" />
              </a>
            </div>
          </div>
          <div className="mx-auto flex items-center justify-center">
            <div className="inline-block rounded-full overflow-hidden object-cover object-center border-4 border-white">
              <img
                alt="Profile picture"
                className="hover:scale-150 transition-transform duration-200 ease-in-out"
                height="300"
                width="300"
                src="https://media.licdn.com/dms/image/D4E03AQHs4Vu0dQds3A/profile-displayphoto-shrink_800_800/0/1709576798486?e=1715212800&v=beta&t=e230PmY782e7GePD2cVea3OqjzypHB86vSI-2GCMkCQ"
                style={{
                  aspectRatio: "300/300",
                  objectFit: "cover",
                }}
              />
            </div>
          </div>
        </section>
        <section id="#projects" className="grid gap-6 lg:h-[calc(100vh-14px)] lg:w-full justify-items-center items-center mt-12 sm:mt-0">
          <div className="">
            <h2 className="text-3xl font-bold tracking-tighter peer">My Projects</h2>
            <p className="text-gray-500 dark:text-gray-400">Check out my work</p>
          </div>
          <div className="grid gap-8 md:gap-6 lg:grid-cols-2 justify-items-center items-center w-full">
                {
                  projects.map((project, index) => (
                    <ProjectCard key={`project-${index}`} name={project.title} description={project.body} thumbnail={project.thumbnail} url={project.github} index={index} />
                  ))
                }
          </div>
        </section>
        <section id="#skills" className="grid gap-6 lg:h-[calc(100vh-14px)] lg:w-full md:pl-5 items-center">
          <div className="mx-auto">
            <h2 className="text-3xl font-bold tracking-tighter peer">My Skills</h2>
            <p className="text-gray-500 dark:text-gray-400">My technical expertise</p>
          </div>
          <DynamicView>
            <div className="grid gap-4 md:gap-6 grid-cols-2 lg:grid-cols-8 sm:grid-cols-4 h-full">
              {
                skills.map((skill, index) => (
                  <SkillCard key={`skill-${index}`} skill={skill.skill} thumbnail={skill.thumbmail} years={getYearsAgo(skill.started)} index={index} />
                ))
              }
            </div>
          </DynamicView>
        </section>

      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t mt-20">
        <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Acme Inc. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Terms of Service
          </Link>
          <Link className="text-xs hover:underline underline-offset-4" href="#">
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}






